version: '3.7'
# below are the default ports, change the first port to avoid local conflicts
services:
  db:
    ports:
      - '5433:5432'
  django:
    ports:
      - '8009:8000'
  # front-end:
  #   ports:
  #     - '3000:3000'
  mailhog:
    ports:
      - '8025:8025'
  {% if cookiecutter.use_celery == 'y' %}
  flower:
    ports:
      - '5555:5555'
  {% endif %}
